<?php

namespace AppBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * @return Tickets[]
     */
	public function countNumberVisit(string $visit)
    {
        return $this->createQueryBuilder('t')
            ->select('COUNT(t)')
            ->andWhere('t.visit = :visit')
            ->setParameter('visit', $visit)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findAllTicketsByCommand($id)
    {
      return $this->createQueryBuilder('t')
              ->leftJoin('t.command', 'c')
              ->andWhere('c.id = :id')
              ->setParameter('id', $id)
              ->getQuery()
              ->execute();
    }
}
